### ISSUE TITLE
reenact_avatar bug

### ISSUE THREAD

**Issue by icegaomu** [philgras/neural-head-avatars#19]
Download the data which is trained and the reenact is write like below 
```

driving_ckpt = /mnt/d/DESKTOP/neural-head-avatars-main/nha/person_0000.ckpt
target_ckpt = /mnt/d/DESKTOP/neural-head-avatars-main/nha/person_0004.ckpt
driving_tracking_results =  /mnt/d/DESKTOP/neural-head-avatars-main/tracking/person_0000.npz
target_tracking_results =  /mnt/d/DESKTOP/neural-head-avatars-main/tracking/person_0004.npz
neutral_driving_frame = 0
neutral_target_frame = 0
outpath =  /mnt/d/DESKTOP/neural-head-avatars-main/experiment/change.mp4
```

run    python python_scripts/reenact_avatar.py --config configs/reenactment.ini
and the error is below hope you can jive me some advice !

```
An exception occurred in telemetry logging.Disabling telemetry to prevent further exceptions.
Traceback (most recent call last):
  File "/home/csy/anaconda3/envs/neural_ava/lib/python3.9/site-packages/iopath/common/file_io.py", line 946, in __log_tmetry_keys
    handler.log_event()
  File "/home/csy/anaconda3/envs/neural_ava/lib/python3.9/site-packages/iopath/common/event_logger.py", line 97, in log_event
    del self._evt
AttributeError: _evt
/home/csy/anaconda3/envs/neural_ava/lib/python3.9/site-packages/pytorch3d/structures/meshes.py:1108: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  self._edges_packed = torch.stack([u // V, u % V], dim=1)
An exception occurred in telemetry logging.Disabling telemetry to prevent further exceptions.
Traceback (most recent call last):
  File "/home/csy/anaconda3/envs/neural_ava/lib/python3.9/site-packages/iopath/common/file_io.py", line 946, in __log_tmetry_keys
    handler.log_event()
  File "/home/csy/anaconda3/envs/neural_ava/lib/python3.9/site-packages/iopath/common/event_logger.py", line 97, in log_event
    del self._evt
AttributeError: _evt
rm: cannot remove '/tmp/scene_reenactment_drive/*': No such file or directory
rm: cannot remove '/tmp/scene_reenactment_pred/*': No such file or directory
  0%|          | 0/499 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/csy/anaconda3/envs/neural_ava/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/d/DESKTOP/neural-head-avatars-main/python_scripts/reenact_avatar.py", line 39, in reenact_avatar
    rgb_driving = driving_model.forward(batch, symmetric_rgb_range=False)[:, :3].clamp(0,1)
  File "/mnt/d/DESKTOP/neural-head-avatars-main/nha/models/nha_optimizer.py", line 1844, in forward
    rgba_pred = self._render_rgba(offsets_verts, K, RT, H, W, expr=expr, pose=pose, mouth_cond=mouth_conditioning,
  File "/mnt/d/DESKTOP/neural-head-avatars-main/nha/models/nha_optimizer.py", line 772, in _render_rgba
    frequencies_masked = torch.sum(frequencies[n_masked] * region_weights_masked.unsqueeze(-1), dim=1)
RuntimeError: CUDA error: unknown error
```

and this is my envirment

```
_libgcc_mutex             0.1                 conda_forge    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
_openmp_mutex             4.5                       2_gnu    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
absl-py                   1.1.0                    pypi_0    pypi
aiohttp                   3.8.1                    pypi_0    pypi
aiosignal                 1.2.0                    pypi_0    pypi
argon2-cffi               21.3.0             pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
argon2-cffi-bindings      21.2.0           py39hb9d737c_2    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
asttokens                 2.0.5              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
astunparse                1.6.3                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     21.4.0             pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
backports                 1.0                        py_2    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
blas                      1.0                         mkl    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
bleach                    5.0.0              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
brotli                    1.0.9                h166bdaf_7    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
brotli-bin                1.0.9                h166bdaf_7    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
brotlipy                  0.7.0           py39hb9d737c_1004    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
bzip2                     1.0.8                h7f98852_4    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
ca-certificates           2022.6.15            ha878542_0    conda-forge
cachetools                5.2.0                    pypi_0    pypi
certifi                   2022.6.15                pypi_0    pypi
cffi                      1.15.0           py39hd667e15_1    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
charset-normalizer        2.0.12             pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
chumpy                    0.70                     pypi_0    pypi
colorama                  0.4.5              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
configargparse            1.5.3                    pypi_0    pypi
cpbd                      1.0.7                    pypi_0    pypi
cryptography              37.0.1           py39h9ce1e76_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
cudatoolkit               11.3.1               h2bc3f7f_2    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
cycler                    0.11.0             pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
dataclasses               0.8                pyhc8e2a94_3    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
dbus                      1.13.6               he372182_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
debugpy                   1.6.0            py39h5a03fae_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
entrypoints               0.4                pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
executing                 0.8.3              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
expat                     2.4.8                h27087fc_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
face-alignment            1.3.5                    pypi_0    pypi
face-detection-tflite     0.5.0                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
flatbuffers               1.12                     pypi_0    pypi
flit-core                 3.7.1              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
fontconfig                2.14.0               h8e229c2_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
fonttools                 4.33.3           py39hb9d737c_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
freetype                  2.10.4               h0708190_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
frozenlist                1.3.0                    pypi_0    pypi
fsspec                    2022.5.0                 pypi_0    pypi
fvcore                    0.1.5.post20220512    pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
gast                      0.4.0                    pypi_0    pypi
giflib                    5.2.1                h36c2ea0_2    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
glib                      2.69.1               h4ff587b_1    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
gmp                       6.2.1                h58526e2_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
gnutls                    3.6.13               h85f3911_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
google-auth               2.8.0                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.47.0                   pypi_0    pypi
gst-plugins-base          1.14.0               hbbd80ab_1    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
gstreamer                 1.14.0               h28cd5cc_2    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
h5py                      3.7.0                    pypi_0    pypi
icu                       58.2              hf484d3e_1000    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
idna                      3.3                pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
imageio                   2.19.3                   pypi_0    pypi
importlib-metadata        4.11.4           py39hf3d152e_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
importlib_resources       5.8.0              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
intel-openmp              2021.4.0          h06a4308_3561    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
iopath                    0.1.9              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ipykernel                 6.15.0             pyh210e3f2_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ipython                   8.4.0            py39hf3d152e_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ipython-genutils          0.2.0                    pypi_0    pypi
ipython_genutils          0.2.0                      py_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ipywidgets                7.7.1              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jedi                      0.18.1           py39hf3d152e_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9e                   h166bdaf_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jsonschema                4.6.0              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jupyter                   1.0.0            py39hf3d152e_7    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jupyter_client            7.3.4              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jupyter_console           6.4.4              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.1              pyhd8ed1ab_2    conda-forge
jupyter_core              4.10.0           py39hf3d152e_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jupyter_highlight_selected_word 0.2.0           py39hf3d152e_1005    conda-forge
jupyter_latex_envs        1.4.6           pyhd8ed1ab_1002    conda-forge
jupyter_nbextensions_configurator 0.4.1            py39hf3d152e_2    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jupyterlab_widgets        1.1.1              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jupyterthemes             0.20.0                     py_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
keras                     2.9.0                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.4.3            py39hf939315_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
lame                      3.100             h7f98852_1001    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
lcms2                     2.12                 hddcbb42_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
lerc                      3.0                  h9c3ff4c_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
lesscpy                   0.15.0             pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libbrotlicommon           1.0.9                h166bdaf_7    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libbrotlidec              1.0.9                h166bdaf_7    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libbrotlienc              1.0.9                h166bdaf_7    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libclang                  14.0.1                   pypi_0    pypi
libdeflate                1.12                 h166bdaf_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libffi                    3.3                  h58526e2_2    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libgomp                   12.1.0              h8d9b700_16    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libiconv                  1.17                 h166bdaf_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libnsl                    2.0.0                h7f98852_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libpng                    1.6.37               h21135ba_2    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libsodium                 1.0.18               h36c2ea0_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libtiff                   4.4.0                hc85c160_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libuuid                   2.32.1            h7f98852_1000    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libuv                     1.43.0               h7f98852_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libwebp                   1.2.2                h3452ae3_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libwebp-base              1.2.2                h7f98852_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libxcb                    1.13              h7f98852_1004    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libxml2                   2.9.14               h74e7548_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
libxslt                   1.1.35               h4e12654_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
libzlib                   1.2.12               h166bdaf_1    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
llvmlite                  0.38.1                   pypi_0    pypi
lpips                     0.1.4                    pypi_0    pypi
lxml                      4.9.0            py39hb9d737c_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
markdown                  3.3.7                    pypi_0    pypi
markupsafe                2.1.1            py39hb9d737c_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
matplotlib-base           3.5.2            py39h700656a_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
mistune                   0.8.4           py39h3811e60_1005    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
mkl                       2021.4.0           h06a4308_640    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
mkl-service               2.4.0            py39h7e14d7c_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
mkl_fft                   1.3.1            py39h0c7bc48_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
mkl_random                1.2.2            py39hde0f152_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
multidict                 6.0.2                    pypi_0    pypi
munkres                   1.0.7                      py_1    http://mirrors.ustc.edu.cn/anaconda/cloud/bioconda
nb_conda                  2.2.1                    unix_6    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
nb_conda_kernels          2.3.1            py39hf3d152e_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
nbclient                  0.6.4              pyhd8ed1ab_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
nbconvert                 6.5.0              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
nbconvert-core            6.5.0              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
nbconvert-pandoc          6.5.0              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
nbformat                  5.4.0              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ncurses                   6.3                  h27087fc_1    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
nettle                    3.6                  he412f7d_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
networkx                  2.8.4                    pypi_0    pypi
nha                       0.1.0                     dev_0    <develop>
notebook                  6.4.12             pyha770c72_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
numba                     0.55.2                   pypi_0    pypi
numpy                     1.21.0                   pypi_0    pypi
numpy-base                1.22.3           py39hf524024_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
oauthlib                  3.2.0                    pypi_0    pypi
opencv-python             4.6.0.66                 pypi_0    pypi
openh264                  2.1.1                h780b84a_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
openjpeg                  2.4.0                hb52868f_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
openssl                   1.1.1p               h166bdaf_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 21.3               pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pandoc                    2.18                 ha770c72_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
parso                     0.8.3              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pcre                      8.45                 h9c3ff4c_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pickleshare               0.7.5                   py_1003    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pillow                    9.1.1            py39hae2aec6_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pip                       22.1.2             pyhd8ed1ab_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
ply                       3.11                       py_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
portalocker               2.4.0            py39hf3d152e_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
prometheus_client         0.14.1             pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
prompt-toolkit            3.0.29             pyha770c72_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
prompt_toolkit            3.0.29               hd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
protobuf                  3.19.4                   pypi_0    pypi
psutil                    5.9.1            py39hb9d737c_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pthread-stubs             0.4               h36c2ea0_1001    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pygments                  2.12.0             pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pyqt                      5.9.2            py39h2531618_6    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
pyrsistent                0.18.1           py39hb9d737c_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pysocks                   1.7.1            py39hf3d152e_5    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python                    3.9.12               h12debd9_1    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
python-dateutil           2.8.2              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python-fastjsonschema     2.15.3             pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python_abi                3.9                      2_cp39    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
pytorch                   1.11.0          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
pytorch-lightning         1.2.4                    pypi_0    pypi
pytorch-msssim            0.2.1                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pytorch3d                 0.6.2           py39_cu113_pyt1110    pytorch3d
pywavelets                1.3.0                    pypi_0    pypi
pyyaml                    6.0              py39hb9d737c_4    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pyzmq                     23.2.0                   pypi_0    pypi
qt                        5.9.7                h5867ecd_1    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
qtconsole                 5.3.1              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
qtconsole-base            5.3.1              pyha770c72_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
qtpy                      2.1.0              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
readline                  8.1.2                h0f457ee_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
requests                  2.28.0             pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.8                      pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scikit-learn              1.1.1                    pypi_0    pypi
scipy                     1.8.1                    pypi_0    pypi
send2trash                1.8.0              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
setuptools                62.6.0           py39hf3d152e_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
sip                       4.19.13          py39h295c915_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
six                       1.16.0             pyh6c4a22f_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
soupsieve                 2.3.2.post1              pypi_0    pypi
sqlite                    3.38.5               h4ff8645_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
stack_data                0.3.0              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tabulate                  0.8.10             pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tensorboard               2.9.1                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.9.1                    pypi_0    pypi
tensorflow-estimator      2.9.0                    pypi_0    pypi
tensorflow-io-gcs-filesystem 0.26.0                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.15.0           py39hf3d152e_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2022.5.4                 pypi_0    pypi
tinycss2                  1.1.1              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tk                        8.6.12               h27826a3_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
torch                     1.10.2+cu113             pypi_0    pypi
torchaudio                0.11.0               py39_cu113    pytorch
torchscope                0.1.0                    pypi_0    pypi
torchvision               0.11.3+cu113             pypi_0    pypi
tornado                   6.1              py39hb9d737c_3    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tqdm                      4.64.0             pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
traitlets                 5.3.0              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
typing_extensions         4.2.0              pyha770c72_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tzdata                    2022a                h191b570_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
unicodedata2              14.0.0           py39hb9d737c_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
vht                       0.1.0                     dev_0    <develop>
wcwidth                   0.2.5              pyh9f0ad1d_2    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
webencodings              0.5.1                    pypi_0    pypi
werkzeug                  2.1.2                    pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
widgetsnbextension        3.6.1              pyha770c72_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
wrapt                     1.14.1                   pypi_0    pypi
xorg-libxau               1.0.9                h7f98852_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xz                        5.2.5                h516909a_1    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
yacs                      0.1.8              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
yaml                      0.2.5                h7f98852_2    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
yarl                      1.7.2                    pypi_0    pypi
zeromq                    4.3.4                h9c3ff4c_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
zlib                      1.2.12               h166bdaf_1    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
zstd                      1.5.2                h8a70e8d_1    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge

```

tanks a lot!

**Comment by icegaomu** [comment]
I try again and it  said the cuda is out of memory  so i set the batch size=1 and it is work! but i still don't know where are python_scripts/optimize_avatar.py and --config configs/avatar_optimization.ini

**Comment by malteprinzler** [comment]
Glad that worked. You're completely right, there was a type in the instructions: 

- python_scripts/optimize_avatar.py -> python_scripts/optimize_nha.py
- configs/avatar_optimization.ini -> configs/optimize_avatar.ini

The respective lines are now corrected in the readme. Thx for pointing them out!
